dist:
    trusty

language:
    generic

sudo:
    required

group:
    travis_latest

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq curl git grep pcregrep sed libcurl4-openssl-dev libelf-dev libdw-dev cmake gcc binutils-dev libiberty-dev zlib1g-dev
    - sudo pip install bashate

script:
    - sudo bash ./main.sh -xt validate_newline
    - sudo bash ./main.sh -xt validate_bashate
    - sudo bash ./main.sh -xt validate_shellcheck
    - sudo bash ./main.sh -xt run_install
    - sudo bash ./main.sh -xt run_generate

matrix:
    fast_finish:   true

after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  cd kcov-master &&
  mkdir build &&
  cd build &&
  sudo cmake .. &&
  sudo make &&
  sudo make install &&
  cd ../.. &&
  rm -rf kcov-master &&
  mkdir -p coverage &&
  kcov coverage sudo bash ./main.sh -t &&
  bash <(curl -s https://codecov.io/bash)

notifications:
    webhooks:      https://www.travisbuddy.com/
